kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: opentelemetry-operator
rules:
  - apiGroups:
      - operator.openshift.io
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - opentelemetries.operator.openshift.io
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - services
      - pods
      - configmaps
      - secrets
      - names
      - nodes
      - pods/eviction
      - events
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - deployments
      - replicasets
    verbs:
      - "*"
