kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: opentelemetry-role-binding
subjects:
  - kind: ServiceAccount
    name: opentelemetry-operator
    namespace: opentelemetry-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: opentelemetry-operator
